version: "2.4"

services:
  client:
    container_name: client
    build: ./client
    restart: always
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
  server:
    container_name: server
    build:
      dockerfile: Dockerfile
      context: ./server
      target: development
    env_file:
      - ./server/.env
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
    ports:
      - 5000:5000
    depends_on:
      - postgres
      - redis
  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    env_file:
      - ./server/.env
    ports:
      - "5432:5432"
    volumes:
      - docker-nest-postgres:/var/lib/postgresql/data
  prisma-studio:
    container_name: prisma-studio
    image: timothyjmiller/prisma-studio:latest
    restart: unless-stopped
    env_file:
      - ./server/.env
    ports:
      - 5555:5555
    depends_on:
      - postgres
      - server
#   redis:
#     image: "redislabs/rejson:2.0.0"
#     ports:
#       - "6379:6379"
#     volumes:
#       - "redisdata:/data"
volumes:
  docker-nest-postgres:
  redis:
    driver: local
